// Copyright (C) 2026 Industrial Algebra
// SPDX-License-Identifier: Apache-2.0

//! # Baedeker FFI
//!
//! C-compatible ABI for embedding the Baedeker WebAssembly runtime into host
//! applications on any platform. Compiles to a static library (`staticlib`)
//! and shared library (`cdylib`); the C header is `include/baedeker.h`
//! (regenerated by `build.rs` on every build — commit the diff when the API
//! changes).
//!
//! ## Model
//!
//! - [`BaedekerModule`] — a decoded, validated, lowered module. Compile once,
//!   instantiate many times. Freed with `baedeker_module_free`.
//! - [`BaedekerInstance`] — an instantiated module with its own store.
//!   Self-contained: the module handle may be freed once the instance exists.
//!
//! Every fallible function returns [`BaedekerStatus`]; on non-`Ok`, the
//! thread-local `baedeker_last_error` carries a human-readable message.
//!
//! ## Safety contract
//!
//! - Handles are opaque, single-owner, and **not** thread-safe: an instance
//!   may be used from any one thread at a time.
//! - Raw memory pointers (`baedeker_instance_memory_data`) are invalidated by
//!   any subsequent call into the instance (memory may grow and reallocate).
//! - All panics are caught at the boundary and reported as
//!   `BaedekerStatusPanic`.
//!
//! ## Not in this version
//!
//! Reference-typed values (funcref/externref), multi-module linking, and
//! imported memories/globals/tables — they arrive with their consumers
//! (Swift package, GPU host module).

pub mod api;
pub mod api2;
pub mod error;
pub mod value;

pub use api::{BaedekerHostFn, BaedekerInstance, BaedekerModule};
pub use error::BaedekerStatus;
pub use value::{BaedekerValue, BaedekerValueData, BaedekerValueTag};
