[package]
name = "baedeker-cli"
description = "Baedeker WebAssembly runtime — command-line test harness"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"

[dependencies]
baedeker-core = { path = "../baedeker-core", version = "0.1.0", features = ["std", "aot"] }

[dev-dependencies]
baedeker-testdata = { path = "../baedeker-testdata" }
